services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    environment:
          JUDGE0_URL: http://server:2358
          LANGUAGE_ID: "54"
          DATABASE_URL: postgresql+psycopg2://${APP_DB_USER}:${APP_DB_PASSWORD}@api_database:5432/${APP_DB_NAME}
    ports:
      - "8000:8000"
    depends_on:
      - server
      - redis
      - api_database

  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0/judge0.conf:/judge0.conf:ro
    env_file:
      - ./judge0/judge0.conf
    ports:
      - "2358:2358"
    privileged: true
    restart: always

  worker:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0/judge0.conf:/judge0.conf:ro
    env_file:
      - ./judge0/judge0.conf
    privileged: true
    restart: always

  db:
    image: postgres:16.2
    env_file:
      - ./judge0/judge0.conf
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always

  api_database:
    image: postgres:16.2
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - appdb:/var/lib/postgresql/data/
    restart: always

  test_database:
    image: postgres:16.2
    profiles: ["test"]
    environment:
      POSTGRES_DB: app_database_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5434:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d app_database_test"]
      interval: 2s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7.2.4
    command:
      [
        "bash",
        "-c",
        "docker-entrypoint.sh --appendonly no --requirepass \"$$REDIS_PASSWORD\""
      ]
    env_file:
      - ./judge0/judge0.conf
    restart: always

volumes:
  data:
  appdb:
