export const elementaryAlgorithmCategories = [
  {
    id: "prelucrarea-cifrelor",
    eyebrow: "01 · Cifre",
    title: "Prelucrarea cifrelor",
    description: "Învață cum extragem, numărăm, filtrăm și reconstruim cifrele unui număr.",
    accent: "cyan",
    icon: "123",
    lessons: [
      "suma-cifrelor",
      "numarul-de-cifre",
      "numarul-de-aparitii-ale-unei-cifre",
      "rasturnatul-unui-numar",
      "numar-palindrom",
      "eliminarea-cifrelor-pare",
    ],
  },
  {
    id: "divizibilitate",
    eyebrow: "02 · Divizori",
    title: "Divizibilitate",
    description: "Testează împărțirea exactă și lucrează cu divizorii unui număr natural.",
    accent: "violet",
    icon: "%",
    lessons: [
      "divizorii-unui-numar",
      "numarul-divizorilor",
      "suma-divizorilor",
    ],
  },
  {
    id: "numere-prime",
    eyebrow: "03 · Primalitate",
    title: "Numere prime și factorizare",
    description: "Recunoaște numerele prime și descompune un număr în factorii săi primi.",
    accent: "amber",
    icon: "P",
    lessons: [
      "verificarea-unui-numar-prim",
      "numere-prime-dintr-un-interval",
      "descompunerea-in-factori-primi",
    ],
  },
  {
    id: "cmmdc-cmmmc",
    eyebrow: "04 · Euclid",
    title: "CMMDC, CMMMC și numere prime între ele",
    description: "Folosește algoritmul lui Euclid pentru relațiile fundamentale dintre două numere.",
    accent: "emerald",
    icon: "∩",
    lessons: [
      "cmmdc-algoritmul-lui-euclid",
      "cmmmc",
      "numere-prime-intre-ele",
    ],
  },
  {
    id: "minime-maxime",
    eyebrow: "05 · Vectori",
    title: "Minime și maxime în vectori",
    description: "Păstrează cele mai mici sau cele mai mari valori în timpul unei singure parcurgeri.",
    accent: "rose",
    icon: "↕",
    lessons: [
      "minimul-si-maximul-unui-vector",
      "cele-mai-mari-doua-valori-distincte",
      "cele-mai-mici-doua-valori-distincte",
      "cele-mai-mari-trei-valori-distincte",
      "cele-mai-mici-trei-valori-distincte",
    ],
  },
  {
    id: "vectori-frecventa",
    eyebrow: "06 · Frecvență",
    title: "Vectori de frecvență",
    description: "Transformă o listă de valori într-un tabel rapid de numărări sau prezențe.",
    accent: "blue",
    icon: "f[x]",
    lessons: [
      "vector-frecventa-numarul-aparitiilor",
      "vector-aparitii-exista-sau-nu",
    ],
  },
  {
    id: "cautare-interclasare",
    eyebrow: "07 · Vectori sortați",
    title: "Căutare și interclasare",
    description: "Profită de ordinea elementelor pentru a căuta rapid sau pentru a combina vectori.",
    accent: "lime",
    icon: "⌕",
    lessons: ["cautare-binara", "interclasarea-a-doi-vectori-sortati"],
  },
  {
    id: "secvente-consecutive",
    eyebrow: "08 · Secvențe",
    title: "Secvențe consecutive",
    description: "Urmărește o secvență curentă și recordul ei în timp ce valorile sunt citite.",
    accent: "orange",
    icon: "▰▰▰",
    lessons: [
      "cea-mai-lunga-secventa-pozitiva",
      "cea-mai-lunga-secventa-de-numere-egale",
      "cea-mai-lunga-secventa-strict-crescatoare",
    ],
  },
] as const;

export type ElementaryCategoryAccent =
  (typeof elementaryAlgorithmCategories)[number]["accent"];
